version: "3.7"
services:
  rabbitmq:
    image: rabbitmq

  api:
    image: admissionapi
    deploy:
      replicas: 4
    depends_on:
      - rabbitmq
    ports:
      - "3001:3000"

  db:
    image: admissiondb
    depends_on:
      - rabbitmq
    volumes:
      - admissiondb:/volume/

volumes:
    admissiondb:
        driver: local