version: "3.7"
services:
  rabbitmq:
    image: rabbitmq

  api:
    image: admissionapi
    deploy:
      replicas: 4
    resources:
      limits:
        cpus: "0.5"
        memory: 10M    
    restart_policy:
      condition: on-failure
    depends_on:
      - rabbitmq
    ports:
      - "3001:3000"

  db:
    image: admissiondb
    resources:
      limits:
        cpus: "0.5"
        memory: 10M    
    restart_policy:
      condition: on-failure
    depends_on:
      - rabbitmq
    volumes:
      - admissiondb:/volume/

volumes:
    admissiondb:
        driver: local