version: "3.7"
services:
  rabbitmq:
    image: rabbitmq
    volumes:
      - ./rabbitmq_enabled_plugins:/etc/rabbitmq/enabled_plugins

  api:
    image: admissionapi
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: "0.5"
          memory: 100M
    depends_on:
      - rabbitmq
    ports:
      - "3001:3000"

  db:
    image: admissiondb
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 100M
    depends_on:
      - rabbitmq
    volumes:
      - admissiondb:/volume/

volumes:
    admissiondb:
        driver: local